[package]
name = "kohakuefda"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "_native"
crate-type = ["cdylib"]
path = "src/kohakuefda-rs/lib.rs"

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
